nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.10.3.cjs

# Allow React 19 even though some packages request React 18
peerDependencyRules:
  allowedVersions:
    react: "19"
    react-dom: "19"
